/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArtText: typeof import('./src/components/macro/ArtText.vue')['default']
    CountDown: typeof import('./src/components/macro/CountDown.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    HelpCard: typeof import('./src/components/macro/HelpCard.vue')['default']
    LeftEdit: typeof import('./src/components/macro/LeftEdit.vue')['default']
    NavigationBar: typeof import('./src/components/macro/NavigationBar.vue')['default']
    PostTable: typeof import('./src/components/PostTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
